services:
  app:
    build:
      context: ./simexRoutex
      dockerfile: Dockerfile
    container_name: simex-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./simexRoutex:/var/www # Sincroniza el código con PHP
    networks:
      - simex-network

  nginx:
    image: nginx:alpine
    container_name: simex-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      # ESTO ES LO QUE ARREGLA EL 404:
      - ./simexRoutex:/var/www:ro # Nginx necesita ver la carpeta 'public' aquí
      - ./simexRoutex/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - simex-network
    depends_on:
      - app

networks:
  simex-network:
    driver: bridge
