server {
    listen 80;
    index index.php index.html;
    root /var/www/simexRoutex/public; # Asegúrate de que termina en /public

    location / {
        # Esto obliga a que todo pase por el index.php de Laravel
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/simexRoutex/public/index.php;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location /storage {
        alias /var/www/storage/app/public;
        autoindex on;
    }

    error_page 404 = @fallback;
    location @fallback {
        return 200 "Nginx esta leyendo este archivo pero no encuentra el script de PHP en /var/www/public";
    }
}
