server {
    listen 80;
    index index.php index.html;
    root /var/www/public;

    # Importante: para que Nginx no se pierda con las rutas de Laravel
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        # Comprobamos que el archivo existe antes de pasarlo a PHP
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        # Conexión al contenedor 'app' en el puerto 9000
        fastcgi_pass app:9000;
        fastcgi_index index.php;

        include fastcgi_params;
        # Forzamos la ruta absoluta que acabamos de ver en tu terminal
        fastcgi_param SCRIPT_FILENAME /var/www/public/index.php;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        fastcgi_read_timeout 600;
    }

    client_max_body_size 100M;
}
