server {
    # este es el bloque del server, está escuchando en el 80, public es la carpeta a la que puede acceder nginx. El index sirve por si se entra en la raiz del proyecto sirva directamente el index
    listen 80;
    server_name localhost;
    root /var/www/public;
    index index.php index.html;

    # nginx busca el archivo con ese nombre en caso de no encontralo se lo envia a index.php con el parametro (ese nombre)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # 127 - nginx pasa a php que está escuchando en el 9000, con el Script filename le dice que fichero ha de ejecutar
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
