name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: push image to docker hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u jeanfg --password-stdin

      - name: build image
        run: docker build -t jeanfg/devops-qr-code-backend:latest .

      - name: Push image
        run: docker push jeanfg/devops-qr-code-backend:latest
        
